version: '3.3'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
     - "2181:2181"

  kafka:
    image: wurstmeister/kafka   # https://github.com/wurstmeister/kafka-docker  to  Add more brokers:docker-compose scale kafka=3
    container_name: kafka_server  
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "my-topic-rk:1:1, my-topic-2:1:1"   #topic_name:partition:replicas

  producer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: Producer
    depends_on:
      - kafka
    restart: on-failure
    ports:
      - "9094:80"

  consumer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.consumer
    container_name: Consumer
    depends_on:
      - kafka
    restart: on-failure
    ports:
      - "9095:80"

      