FROM python:3.9
LABEL maintainer="Rahul Kataria <rahulkataria3355@gmail.com>"
 
RUN apt update && apt install -y default-jre
WORKDIR /app


COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY app/consumer.py .

CMD [ "python", "consumer.py" ]
