FROM python:3.9

LABEL maintainer="Rahul Kataria <rahulkataria3355@gmail.com>"

# RUN apt-get update && apt-get install -y default-jre

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./app /app

EXPOSE 80

CMD ["python", "-u", "consumer.py"]
